// export const API_PATH = 'http://localhost:5000';
export const API_PATH = '';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const RECEIVE_USER_CHATS = 'RECEIVE_USER_CHATS';
export const FETCH_USER_CHATS_REQUEST = 'FETCH_USER_CHATS_REQUEST';

export const RECEIVE_USER_GROUPS = 'RECEIVE_USER_GROUPS';
export const FETCH_USER_GROUPS_REQUEST = 'FETCH_USER_GROUPS_REQUEST';

export const ADD_GROUP_REQUEST = 'ADD_GROUP_REQUEST';
export const ADD_GROUP_SUCCESS = 'ADD_GROUP_SUCCESS';
export const ADD_GROUP_FAILURE = 'ADD_GROUP_FAILURE';

export const UPDATE_GROUP_TITLE_REQUEST = 'UPDATE_GROUP_TITLE_REQUEST';
export const UPDATE_GROUP_TITLE_SUCCESS = 'UPDATE_GROUP_TITLE_SUCCESS';
export const UPDATE_GROUP_TITLE_FAILURE = 'UPDATE_GROUP_TITLE_FAILURE';

export const UPDATE_GROUP_MEMBERS_REQUEST = 'UPDATE_GROUP_MEMBERS_REQUEST';
export const UPDATE_GROUP_MEMBERS_SUCCESS = 'UPDATE_GROUP_MEMBERS_SUCCESS';
export const UPDATE_GROUP_MEMBERS_FAILURE = 'UPDATE_GROUP_MEMBERS_FAILURE';

export const DELETE_GROUP_REQUEST = 'DELETE_GROUP_REQUEST';
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_FAILURE = 'DELETE_GROUP_FAILURE';

export const ADD_CHAT_REQUEST = 'ADD_CHAT_REQUEST';
export const ADD_CHAT_SUCCESS = 'ADD_CHAT_SUCCESS';
export const ADD_CHAT_FAILURE = 'ADD_CHAT_FAILURE';
export const ADD_CHAT_CLOSE = 'ADD_CHAT_CLOSE';

export const READ_CHAT_REQUEST = 'READ_CHAT_REQUEST';
export const READ_CHAT = 'READ_CHAT';

export const DELETE_CHAT_REQUEST = 'DELETE_CHAT_REQUEST';
export const DELETE_CHAT_SUCCESS = 'DELETE_CHAT_SUCCESS';
export const DELETE_CHAT_FAILURE = 'DELETE_CHAT_FAILURE';

export const RECEIVE_PROTECTED_DATA = 'RECEIVE_PROTECTED_DATA';
export const FETCH_PROTECTED_DATA_REQUEST = 'FETCH_PROTECTED_DATA_REQUEST';

export const UPDATE_USER_DATA_REQUEST = 'UPDATE_USER_DATA_REQUEST';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const UPDATE_USER_DATA_FAILURE = 'UPDATE_USER_DATA_FAILURE';
export const UPDATE_USER_DATA_CLOSE = 'UPDATE_USER_DATA_CLOSE';

export const UPDATE_USER_PHOTO_REQUEST = 'UPDATE_USER_PHOTO_REQUEST';
export const UPDATE_USER_PHOTO = 'UPDATE_USER_PHOTO';
export const UPDATE_USER_PHOTO_FAILURE = 'UPDATE_USER_PHOTO_FAILURE';

export const UPDATE_GROUP_PHOTO_REQUEST = 'UPDATE_GROUP_PHOTO_REQUEST';
export const UPDATE_GROUP_PHOTO = 'UPDATE_GROUP_PHOTO';
export const UPDATE_GROUP_PHOTO_FAILURE = 'UPDATE_GROUP_PHOTO_FAILURE';

export const RECEIVE_USERS_DATA = 'RECEIVE_USERS_DATA';
export const FETCH_USERS_DATA_REQUEST = 'FETCH_USERS_DATA_REQUEST';
export const CLEAN_USERS_DATA = 'CLEAN_USERS_DATA';

export const RECEIVE_UNAUTHORIZED_USER_DATA = 'RECEIVE_UNAUTHORIZED_USER_DATA';
export const FETCH_UNAUTHORIZED_USER_DATA_REQUEST = 'FETCH_UNAUTHORIZED_USER_DATA';
export const FETCH_UNAUTHORIZED_USER_DATA_FAILURE = 'FETCH_UNAUTHORIZED_USER_DATA_FAILURE';
export const CLEAN_UNAUTHORIZED_USER_DATA = 'CLEAN_UNAUTHORIZED_USER_DATA';

export const RECEIVE_CONTACT_LIST = 'RECEIVE_CONTACT_LIST';
export const FETCH_CONTACT_LIST_REQUEST = 'FETCH_CONTACT_LIST_REQUEST';

export const RECEIVE_FILTERED_CONTACT_LIST = 'RECEIVE_FILTERED_CONTACT_LIST';
export const FETCH_FILTERED_CONTACT_LIST_REQUEST = 'FETCH_FILTERED_CONTACT_LIST_REQUEST';
export const CLEAN_CONTACT_LIST = 'CLEAN_CONTACT_LIST';

export const RECEIVE_INVITATION_LIST = 'RECEIVE_INVITATION_LIST';
export const FETCH_INVITATION_LIST_REQUEST = 'FETCH_INVITATION_LIST_REQUEST';