export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';

export const RECEIVE_USER_CHATS = 'RECEIVE_USER_CHATS';
export const FETCH_USER_CHATS_REQUEST = 'FETCH_USER_CHATS_REQUEST';

export const ADD_CHAT_REQUEST = 'ADD_CHAT_REQUEST';
export const ADD_CHAT_SUCCESS = 'ADD_CHAT_SUCCESS';
export const ADD_CHAT_FAILURE = 'ADD_CHAT_FAILURE';
export const ADD_CHAT_CLOSE = 'ADD_CHAT_CLOSE';

export const READ_CHAT_REQUEST = 'READ_CHAT_REQUEST';
export const READ_CHAT = 'READ_CHAT';

export const RECEIVE_PROTECTED_DATA = 'RECEIVE_PROTECTED_DATA';
export const FETCH_PROTECTED_DATA_REQUEST = 'FETCH_PROTECTED_DATA_REQUEST';

export const UPDATE_USER_DATA_REQUEST = 'UPDATE_USER_DATA_REQUEST';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const UPDATE_USER_DATA_FAILURE = 'UPDATE_USER_DATA_FAILURE';
export const UPDATE_USER_DATA_CLOSE = 'UPDATE_USER_DATA_CLOSE';

export const UPDATE_USER_PHOTO_REQUEST = 'UPDATE_USER_PHOTO_REQUEST';
export const UPDATE_USER_PHOTO = 'UPDATE_USER_PHOTO';
export const UPDATE_USER_PHOTO_FAILURE = 'UPDATE_USER_PHOTO_FAILURE';

export const RECEIVE_USERS_DATA = 'RECEIVE_USERS_DATA';
export const FETCH_USERS_DATA_REQUEST = 'FETCH_USERS_DATA_REQUEST';
export const CLEAN_USERS_DATA = 'CLEAN_USERS_DATA';

export const RECEIVE_UNAUTHORIZED_USER_DATA = 'RECEIVE_UNAUTHORIZED_USER_DATA';
export const FETCH_UNAUTHORIZED_USER_DATA_REQUEST=  'FETCH_UNAUTHORIZED_USER_DATA';
export const FETCH_UNAUTHORIZED_USER_DATA_FAILURE = 'FETCH_UNAUTHORIZED_USER_DATA_FAILURE';
export const CLEAN_UNAUTHORIZED_USER_DATA = 'CLEAN_UNAUTHORIZED_USER_DATA';